services: docker
addons:
  sonarcloud:
    organization: "mixeway"
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mixeway/frontend:0.9 .
  - docker push mixeway/frontend:0.9
