services: docker

addons:
  sonarcloud:
    organization: "mixeway"
    token: ${SONAR_TOKEN}
env:
  global:
    - NODE_OPTIONS="–-max_old_space_size=8192"
    - VERSION=1.0.0
jobs:
  include:
#    - stage: sonar
#      script: sonar-scanner -Dsonar.login=${SONAR_TOKEN}
    - stage: build_and_deploy
      script:
      - docker build -t mixeway/frontend:$VERSION .
      - if [[ $TRAVIS_BRANCH == 'master' ]]; then docker push mixeway/frontend:$VERSION; fi
