services: docker
addons:
  sonarcloud:
    organization: "mixeway"
    token:
      secure: ${SONAR_TOKEN}
env:
  global:
    - NODE_OPTIONS="–-max_old_space_size=8192"
    - VERSION=1.0.0
jobs:
  include:
    - stage: sonar
      script: sonar-scanner -Dsonar.projectKey=Mixeway_MixewayFrontend -Dsonar.login=${SONAR_TOKEN}
    - stage: build
      script: docker build -t mixeway/frontend:$VERSION .
    - stage: deploy
      script: docker push mixeway/frontend:$VERSION
      if: branch = master
