export class ExtraConstants {
    TOOLTIP_RUNONCE = 'Start Scan';
    TOOLTIP_DELETE_PROJECT = 'Delete';
    SUCCESS = 'Success';
    FAILURE = 'Failure';
    FAILURE_TEXT = 'Operation failed';
    CODE_OPERATION_CODE_DELETE = 'Project is deleted successfully';
    OPERATION_RUNONCE = 'Scan is launched';
    ASSET_OPERATION_DELETE = 'Asset is successfully deleted';
    WEBAPP_OPERATION_DELETE = 'WebApp is successfully deleted';
    TOOLTIP_EDIT = 'Edit';
  CODE_PROJECT_EDIT = 'Edit Code Project';
  PROJECT_CODE_PROJECT_DTRACK = 'Pick from configured SCA';
  CREATE_DTRACK_PROJECT = 'Create SCA Project';
  PROJECT_DTRAC_PROJECT_EMPTY = 'DTrack is not imported properly, or there are no projects to import.';
  PROJECT_CODE_PROJECT_SAST = 'Pick from SAST';
  PROJECT_SAST_PROJECT_EMPTY = 'SAST is not imported properly or there are no projects to import.';
  SCANNER_CHECKMARX = 'Checkmarx';
  SCANNER_NEXUSIQ = 'Nexus-IQ';
  SCANNER_FORTIFY = 'Fortify SSC';
  CREATE_SAST_PROJECT1 = 'Create ';
  CREATE_SAST_PROJECT2 = ' Project';
  SCANNER_DTRACK = 'OWASP Dependency Track';
  MISSING_INTEGRATIONS = 'There is no SAST or OpenSource Scanner added. If You did configure plugin in Admin zone, make sure scanner is active by testing it';
  PROJECT_CODE_PROJECT_BRANCH = 'CodeProject branch [default master]';
  PROJECT_CODE_PROJECT_REPOURL = 'URL for GIT Repository';
  PROJECT_CODE_PROJECT_REPOPASSWORD = 'Password to authenticate on above GIR URL (fill if token auth is set)';
  PROJECT_CODE_PROJECT_REPOUSERNAME = 'Username to authenticate on above GIT URL (leave blank if token auth is set)';
}
