name: Deploy to Dockerhub with prod version
on:
  push:
    branches:
      - 'master'
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  publishbrod:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: docker actions build & deploy
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: mixeway/frontend
          tags: 1.2.0
        env:
          NODE_OPTIONS: –-max_old_space_size=8192
