name: Deploy to Dockerhub with prod version
on:
  push:
    branches:
      - 'master'
jobs:
  publishbrod:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: docker actions build & deploy
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: mixeway/frontend
          tags: 1.3.0
        env:
          NODE_OPTIONS: –-max_old_space_size=8192
